name: chat_app
description: "Flutter chat application assignment."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  rename_app: ^1.6.5
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/chat_app.png

# ------------------ APP ICON CONFIG ------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/chat_app.png

  # Android adaptive icon (recommended)
  adaptive_icon_background: "#25D366"
  adaptive_icon_foreground: assets/chat_app.png

  # Optional: remove alpha on iOS (prevents App Store issues)
  remove_alpha_ios: true

